services:    
    web:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./cache:/usr/share/nginx/cache
        ports:
            - "8080:80"
        links: 
            - images
    images:
        image: nginx
        volumes:
            - ./web:/usr/share/nginx/html