services:    
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./geo1.conf:/etc/nginx/geo.conf:ro
        ports:
            - "8080:80"
        links: 
            - nginx_default
            - nginx_uk
            - nginx_us
    nginx_default:
        image: nginx
        volumes:
            - ./nginx/default:/usr/share/nginx/html
    nginx_uk:
        image: nginx
        volumes:
            - ./nginx/uk:/usr/share/nginx/html
    nginx_us:
        image: nginx
        volumes:
            - ./nginx/us:/usr/share/nginx/html